services:
  - type: web
    name: printparkk
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_SECURE
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
      - key: NEXT_PUBLIC_GA_ID
        sync: false
      - key: NODE_VERSION
        value: 20.14.0
